version: '2'
services:
        db:
                container_name: sample_db
                image: postgres:9.5
                volumes:
                        - sample_db:/var/lib/postgresql/data
                environment:
                        - POSTGRES_PASSWORD=root
                        - POSTGRES_USER=root
                        - POSTGRES_DB=sample
                        - PGDATA=/var/lib/postgresql/data/pgdata
                ports:
                        - 5432:5432
volumes:
        sample_db: {}
